### ISSUE TITLE
Warning: custom integration 'pollen_dk' accesses hass.helpers.discovery

### ISSUE THREAD

**Issue by HolgerMiara** [J-Lindvig/Pollen_DK#7]
Moin, 

I found following warning in my logs. It should be addressed before Home Assistant 2025.5. 

```yaml
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: January 7, 2025 at 22:43:47 (2 occurrences)
Last logged: January 7, 2025 at 23:10:26

Detected that custom integration 'pollen_dk' accesses hass.helpers.discovery, which should be updated to import functions used from discovery directly at custom_components/pollen_dk/__init__.py, line 54: hass.helpers.discovery.async_load_platform(CONF_PLATFORM, DOMAIN, conf, config). This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/J-Lindvig/Pollen_DK/issues

``` 
Just as a heads-up =)

Cheers, 
Holger.

**Comment by HolgerMiara** [comment]
Sorry, double to https://github.com/J-Lindvig/Pollen_DK/issues/5

**Comment by sorenfisker** [comment]
Home assistant 2025.5.0:

Logger: homeassistant.setup
Source: setup.py:426
First occurred: 21:39:02 (1 occurrence)
Last logged: 21:39:02

Error during setup of component pollen_dk: 'HomeAssistant' object has no attribute 'helpers'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 426, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/pollen_dk/__init__.py", line 54, in async_setup
    hass.helpers.discovery.async_load_platform(CONF_PLATFORM, DOMAIN, conf, config)
    ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'

**Comment by carentius** [comment]
Same issue

**Comment by helmuto-maker** [comment]
Replacing the contents of `../custom_components/pollen_dk/__init__.py` with this fixes it for me:


```
from __future__ import annotations

import logging

# Import dependencies necessary for new way of adding sensors - line 57
from homeassistant.core import HomeAssistant
from homeassistant.config_entries import ConfigEntry
from homeassistant.helpers import discovery

from .pollen_dk_api import Pollen_DK

from .const import (
    DOMAIN,
    CONF_CLIENT,
    CONF_PLATFORM,
    CONF_POLLEN_TYPES,
    CONF_REGIONS,
    POLLEN_IDS,
    REGION_IDS,
)

_LOGGER: logging.Logger = logging.getLogger(__package__)
_LOGGER = logging.getLogger(__name__)


async def async_setup(hass, config):
    # Get the configuration
    conf = config.get(DOMAIN)
    # If no config, abort
    if conf is None:
        return True

    regionIDs = []
    regions = config[DOMAIN].get(CONF_REGIONS, [])
    if regions:
        for regionKey in regions:
            for regionName, regionID in REGION_IDS.items():
                if regionKey in regionName.lower():
                    regionIDs.append(regionID)
    else:
        regionIDs = REGION_IDS.values()
    _LOGGER.debug(f"Region IDs loaded from config: { regionIDs }")

    pollenIDs = []
    pollens = config[DOMAIN].get(CONF_POLLEN_TYPES, [])
    if pollens:
        for pollenKey in pollens:
            for pollenName, pollenID in POLLEN_IDS.items():
                if pollenKey == pollenName.lower():
                    pollenIDs.append(pollenID)
    else:
        pollenIDs = POLLEN_IDS.values()
    _LOGGER.debug(f"Pollen IDs loaded from config: { pollenIDs }")

    hass.data[DOMAIN] = {CONF_CLIENT: Pollen_DK(regionIDs, pollenIDs)}

    # Add sensors using the new method
    await discovery.async_load_platform(
        hass,
        CONF_PLATFORM,
        DOMAIN,
        conf,
        config
    )

    # Initialization was successful.
    return True
```

**Comment by PCgoDK** [comment]
Ændring af filen /custom_components/pollen_dk/__init__.py til nedenstående og testet med HA 2026.3.1



`from __future__ import annotations

import logging

from .pollen_dk_api import Pollen_DK

from .const import (
    DOMAIN,
    CONF_CLIENT,
    CONF_PLATFORM,
    CONF_POLLEN_TYPES,
    CONF_REGIONS,
    POLLEN_IDS,
    REGION_IDS,
)

_LOGGER: logging.Logger = logging.getLogger(__package__)
_LOGGER = logging.getLogger(__name__)


async def async_setup(hass, config):
    # Get the configuration
    conf = config.get(DOMAIN)
    # If no config, abort
    if conf is None:
        return True

    regionIDs = []
    regions = config[DOMAIN].get(CONF_REGIONS, [])
    if regions:
        for regionKey in regions:
            for regionName, regionID in REGION_IDS.items():
                if regionKey in regionName.lower():
                    regionIDs.append(regionID)
    else:
        regionIDs = REGION_IDS.values()
    _LOGGER.debug(f"Region IDs loaded from config: { regionIDs }")

    pollenIDs = []
    pollens = config[DOMAIN].get(CONF_POLLEN_TYPES, [])
    if pollens:
        for pollenKey in pollens:
            for pollenName, pollenID in POLLEN_IDS.items():
                if pollenKey == pollenName.lower():
                    pollenIDs.append(pollenID)
    else:
        pollenIDs = POLLEN_IDS.values()
    _LOGGER.debug(f"Pollen IDs loaded from config: { pollenIDs }")

    hass.data[DOMAIN] = {CONF_CLIENT: Pollen_DK(regionIDs, pollenIDs)}

    # Add sensors
    # Lazy import: undgå top-level import af helpers for at minimere import-issues
    from homeassistant.helpers.discovery import async_load_platform

    # I 2025.5+ må vi ikke bruge hass.helpers.discovery.*; derfor direkte import og kald
    # (kravet er dokumenteret i HA dev-bloggen om fjernelse af hass.helpers) 
    # Kør som task (samme mønster som før)
    hass.async_create_task(
        async_load_platform(hass, CONF_PLATFORM, DOMAIN, conf, config)
    )

    # Initialization was successful.
    return True`
